name: 提交新功能
description: 请提供详细的新功能请求，以便我们能够更好地了解和实现您的需求。
title: "[Feature] 标题简要描述新功能"
labels: enhancement
body:
  - type: markdown
    attributes:
      value: |
        感谢您提交新功能请求！请填写以下信息，以帮助我们更好地了解和实现您的需求。

  - type: checkboxes
    attributes:
       label: 请在提交新功能请求前确认以下事项
       options:
          - label: 我已经检查过现有的功能请求，确保没有重复的请求？
            required: true

          - label: 我已经详细描述了新功能的需求和预期效果？
            required: true

  - type: input
    id: environment
    attributes:
      label: 环境
      description: 请描述您所使用的Magisk或KernelSU或APatch及其版本等信息。
      placeholder: 例如：Magisk v28.1

  - type: textarea
    id: feature_description
    attributes:
      label: 新功能描述
      description: 请详细描述您希望添加的新功能。
      placeholder: 请在此输入新功能的详细描述。
    validations:
        required: true

  - type: textarea
    id: additional_context
    attributes:
      label: 其他上下文
      description: 如果有其他相关的上下文信息，请在此提供。
      placeholder: 例如：相关的截图、代码等。